# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://notes.peter-baumgartner.net/"


# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-106194253-6"
# Enable comments by entering your Disqus shortname
disqusShortname = "petzi-2"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

languageCode = "en-us"
DefaultContentLanguage = "en"
rssLimit = 100
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."


# pb: Disable comments on the whole site or use it in the header for just one article
# DOES NOT WORK! (I have to do it in every article!)
# TOML: disable_comments = true
# YAML: disable_comments: yes
# disable_comments = yes

title = "Open Science Education" # for RSS feed and Search Engines
theme = "docdock"
themesdir = "themes"

footnotereturnlinkcontents = "â†©"

# for emoji use the following format: :<name of emoji>:
# for example: :wink: ATTN: does not work within Expand shortcode!
# list of names at: https://github.com/afeld/emoji-css/tree/gh-pages/emoji
# list of icons: https://afeld.github.io/emoji-css/ (e.g. convert <i class="em em-anchor"></i> to :anchor:)
# see also: https://emojipedia.org/ (copy & paste)
enableEmoji = true

# Enable .GitInfo object for each page (if the Hugo site is versioned by Git).
# This will then update the Lastmod parameter for each page
# using the last git commit date for that content file.
enableGitInfo = true

# It seems to me that I do not need relativeURLs:
# https://gohugo.io/content-management/urls/#relative-urls
relativeURLs = true # false = default value!


[permalinks]
    post = "/:year/:month/:day/:slug"

[outputs]
    home = [ "HTML", "RSS", "JSON"]

# Configure BlackFriday Markdown rendering.
# See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
    hrefTargetBlank = false  # `true` opens external links in a new tab.
    fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
    smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).


[params]
    # not used anymore: replaced with relURL
    # localSite = "http://127.0.0.1:4321"
    # productionSite = "https://notes.peter-baumgartner.net"

    # Prefix URL to edit current page. Will display an "Edit this page" button
    # on top right hand corner of every page.
    # Useful to give opportunity to people to create merge request for your doc.
    editURL = "https://github.com/petzi53/weblog-notes/edit/master/content/"

    # Author of the site, will be used in meta information
    author = "Peter Baumgartner"
    # Description of the site, will be used in meta information
    description = "Open Science & Data Science Education"

    # options for highlight.js (version, additional languages, and theme)
    # see https://github.com/rbind/yihui/blob/master/config.yaml
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    staticman = false

    noHomeIcon = false # Link in Menue to Homepage (default = false)

    summary_length = 200

    # Show estimated reading time for posts?
    reading_time = true

    # Display comment count? Requires commenting to be enabled.
    comment_count = true

    # Disable search function. It will hide search bar
    noSearch = false # default is false

    # Shows a checkmark for visited pages on the menu
    # if true then a new item Clear History appears:
    showVisitedLinks = false # default is false

    themeStyle = "" # overide base css e.g. "theme-new", "theme-gold", ... "theme" (default)
    themeVariant = "" # choose theme variant "green", "gold" , "gray", "new" "blue" (default)

    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"

    # Javascript and CSS cache are automatically busted when new version of site is generated.
    # Set this to true to disable this behavior (some proxies don't handle well this optimization)
    disableAssetsBusting = false

    # Set this to true to disable copy-to-clipboard button for inline code.
    disableInlineCopyToClipBoard = true

    # A title for shortcuts in menu is set by default. Set this to true to disable it.
    # disableShortcutsTitle = false

    # When using mulitlingual website, disable the switch language button.
    # disableLanguageSwitchingButton = false

# Parameter for the General Data Protection Regulation (GDPR)
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[[menu.shortcuts]]
        pre = "<h3>More</h3>"
        name = "<i class='fa fa-envelope-o'>&nbsp;&nbsp;</i> Contact"
        url = "/contact"
        weight = 5


[[menu.shortcuts]]
        name = "<i class='fa fa-github'>&nbsp;&nbsp;</i> Github repo"
        identifier = "ds"
        url = "https://github.com/petzi53/weblog-notes/"
        weight = 10

[[menu.shortcuts]]
        name = "<i class='fa fa-bullhorn'>&nbsp;&nbsp;</i> Credits"
        url = "/credits"
        weight = 30

[[menu.shortcuts]]
        name = "<i class='fa fa-bookmark'>&nbsp;&nbsp;&nbsp;</i> Categories"
        url = "/categories/"
        weight = 40
[[menu.shortcuts]]
        name = "<i class='fa fa-tags'>&nbsp;&nbsp;</i> Tags"
        url = "/tags/"
        weight = 50
[[menu.shortcuts]]
        name = "<i class='fa fa-rss'>&nbsp;&nbsp;&nbsp;</i> Subscribe"
        url = "/index.xml"
        weight = 60

### some notes about parameter for the YAML front matter for this theme:
### included in /archetypes/default.md
# lastmodifierdisplayname: Peter
# lastmodifieremail: jack.praker@icloud.com
# lastmod: ~
# disable_comments: yes/no


